
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.26.3.  DO NOT EDIT!
//*************************************************************************************

namespace XTC.FMP.MOD.Repository.LIB.Unity
{
    public class MySubjectBase
    {
        /// <summary>
        /// 创建
        /// </summary>
        /// <example>
        /// var data = new Dictionary<string, object>();
        /// data["uid"] = "default";
        /// data["style"] = "default";
        /// model.Publish(/XTC/Repository/Create, data);
        /// </example>
        public const string Create = "/XTC/Repository/Create";

        /// <summary>
        /// 打开
        /// </summary>
        /// <example>
        /// var data = new Dictionary<string, object>();
        /// data["uid"] = "default";
        /// data["source"] = "file";
        /// data["uri"] = "";
        /// data["delay"] = 0f;
        /// model.Publish(/XTC/Repository/Open, data);
        /// </example>
        public const string Open = "/XTC/Repository/Open";

        /// <summary>
        /// 关闭
        /// </summary>
        /// <example>
        /// var data = new Dictionary<string, object>();
        /// data["uid"] = "default";
        /// data["delay"] = 0f;
        /// model.Publish(/XTC/Repository/Close, data);
        /// </example>
        public const string Close = "/XTC/Repository/Close";

        /// <summary>
        /// 销毁
        /// </summary>
        /// <example>
        /// var data = new Dictionary<string, object>();
        /// data["uid"] = "default";
        /// model.Publish(/XTC/Repository/Close, data);
        /// </example>
        public const string Delete = "/XTC/Repository/Delete";
    }
}
