generate:
  active: true
  org_name: XTC
  module_name: Repository
  database_driver: mongodb
  debug: false
  unity_solution: true
publish:
  active: true
  org_name: XTC
  module_name: Repository
  environment: develop 
  repository: grpc://localhost:28000
