
@echo off

REM !!! Generated by the fmp-cli 1.30.0.  DO NOT EDIT!

md Repository\Assets\3rd\fmp-xtc-repository

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-repository-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\Repository\Assets\3rd\fmp-xtc-repository\
