
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.51.0.  DO NOT EDIT!
//*************************************************************************************

using System.Threading.Tasks;
using XTC.FMP.MOD.Repository.LIB.Proto;

namespace XTC.FMP.MOD.Repository.LIB.MVCS
{
    /// <summary>
    /// Agent服务模拟类
    /// </summary>
    public class AgentServiceMock
    {


        public System.Func<AgentCreateRequest, Task<UuidResponse>>? CallCreateDelegate { get; set; } = null;

        public System.Func<AgentUpdateRequest, Task<UuidResponse>>? CallUpdateDelegate { get; set; } = null;

        public System.Func<UuidRequest, Task<AgentRetrieveResponse>>? CallRetrieveDelegate { get; set; } = null;

        public System.Func<UuidRequest, Task<UuidResponse>>? CallDeleteDelegate { get; set; } = null;

        public System.Func<AgentListRequest, Task<AgentListResponse>>? CallListDelegate { get; set; } = null;

        public System.Func<AgentSearchRequest, Task<AgentListResponse>>? CallSearchDelegate { get; set; } = null;

        public System.Func<UuidRequest, Task<PrepareUploadResponse>>? CallPrepareUploadDelegate { get; set; } = null;

        public System.Func<UuidRequest, Task<FlushUploadResponse>>? CallFlushUploadDelegate { get; set; } = null;

        public System.Func<FlagOperationRequest, Task<FlagOperationResponse>>? CallAddFlagDelegate { get; set; } = null;

        public System.Func<FlagOperationRequest, Task<FlagOperationResponse>>? CallRemoveFlagDelegate { get; set; } = null;

    }
}
