
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.26.3.  DO NOT EDIT!
//*************************************************************************************

using System.Threading.Tasks;
using XTC.FMP.MOD.Repository.LIB.Proto;

namespace XTC.FMP.MOD.Repository.LIB.MVCS
{
    /// <summary>
    /// Plugin服务模拟类
    /// </summary>
    public class PluginServiceMock
    {


        public System.Func<PluginCreateRequest, Task<UuidResponse>>? CallCreateDelegate { get; set; } = null;

        public System.Func<PluginUpdateRequest, Task<UuidResponse>>? CallUpdateDelegate { get; set; } = null;

        public System.Func<UuidRequest, Task<PluginRetrieveResponse>>? CallRetrieveDelegate { get; set; } = null;

        public System.Func<UuidRequest, Task<UuidResponse>>? CallDeleteDelegate { get; set; } = null;

        public System.Func<PluginListRequest, Task<PluginListResponse>>? CallListDelegate { get; set; } = null;

        public System.Func<PluginSearchRequest, Task<PluginListResponse>>? CallSearchDelegate { get; set; } = null;

        public System.Func<UuidRequest, Task<PrepareUploadResponse>>? CallPrepareUploadDelegate { get; set; } = null;

        public System.Func<UuidRequest, Task<FlushUploadResponse>>? CallFlushUploadDelegate { get; set; } = null;

    }
}
