
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.26.3.  DO NOT EDIT!
//*************************************************************************************

using XTC.FMP.MOD.Repository.LIB.Proto;
using XTC.FMP.MOD.Repository.LIB.Bridge;

namespace XTC.FMP.MOD.Repository.LIB.MVCS
{

    public class HealthyEchoRequestDTO : IDTO
    {
        public HealthyEchoRequestDTO(HealthyEchoRequest _value)
        {
            Value = _value;    
        }
        public readonly HealthyEchoRequest Value;
    }



    public class HealthyEchoResponseDTO : IDTO
    {
        public HealthyEchoResponseDTO(HealthyEchoResponse _value)
        {
            Value = _value;    
        }
        public readonly HealthyEchoResponse Value;
    }



    public class PluginCreateRequestDTO : IDTO
    {
        public PluginCreateRequestDTO(PluginCreateRequest _value)
        {
            Value = _value;    
        }
        public readonly PluginCreateRequest Value;
    }



    public class PluginUpdateRequestDTO : IDTO
    {
        public PluginUpdateRequestDTO(PluginUpdateRequest _value)
        {
            Value = _value;    
        }
        public readonly PluginUpdateRequest Value;
    }



    public class PluginRetrieveResponseDTO : IDTO
    {
        public PluginRetrieveResponseDTO(PluginRetrieveResponse _value)
        {
            Value = _value;    
        }
        public readonly PluginRetrieveResponse Value;
    }



    public class PluginListRequestDTO : IDTO
    {
        public PluginListRequestDTO(PluginListRequest _value)
        {
            Value = _value;    
        }
        public readonly PluginListRequest Value;
    }



    public class PluginListResponseDTO : IDTO
    {
        public PluginListResponseDTO(PluginListResponse _value)
        {
            Value = _value;    
        }
        public readonly PluginListResponse Value;
    }



    public class PluginSearchRequestDTO : IDTO
    {
        public PluginSearchRequestDTO(PluginSearchRequest _value)
        {
            Value = _value;    
        }
        public readonly PluginSearchRequest Value;
    }



    public class PrepareUploadResponseDTO : IDTO
    {
        public PrepareUploadResponseDTO(PrepareUploadResponse _value)
        {
            Value = _value;    
        }
        public readonly PrepareUploadResponse Value;
    }



    public class FlushUploadResponseDTO : IDTO
    {
        public FlushUploadResponseDTO(FlushUploadResponse _value)
        {
            Value = _value;    
        }
        public readonly FlushUploadResponse Value;
    }



    public class StatusDTO : IDTO
    {
        public StatusDTO(Status _value)
        {
            Value = _value;    
        }
        public readonly Status Value;
    }



    public class BlankRequestDTO : IDTO
    {
        public BlankRequestDTO(BlankRequest _value)
        {
            Value = _value;    
        }
        public readonly BlankRequest Value;
    }



    public class BlankResponseDTO : IDTO
    {
        public BlankResponseDTO(BlankResponse _value)
        {
            Value = _value;    
        }
        public readonly BlankResponse Value;
    }



    public class ScopeRequestDTO : IDTO
    {
        public ScopeRequestDTO(ScopeRequest _value)
        {
            Value = _value;    
        }
        public readonly ScopeRequest Value;
    }



    public class ScopeResponseDTO : IDTO
    {
        public ScopeResponseDTO(ScopeResponse _value)
        {
            Value = _value;    
        }
        public readonly ScopeResponse Value;
    }



    public class UuidRequestDTO : IDTO
    {
        public UuidRequestDTO(UuidRequest _value)
        {
            Value = _value;    
        }
        public readonly UuidRequest Value;
    }



    public class UuidResponseDTO : IDTO
    {
        public UuidResponseDTO(UuidResponse _value)
        {
            Value = _value;    
        }
        public readonly UuidResponse Value;
    }



    public class PluginEntityDTO : IDTO
    {
        public PluginEntityDTO(PluginEntity _value)
        {
            Value = _value;    
        }
        public readonly PluginEntity Value;
    }



}
