
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.35.0.  DO NOT EDIT!
//*************************************************************************************

using XTC.FMP.MOD.Repository.LIB.Proto;
using XTC.FMP.MOD.Repository.LIB.Bridge;

namespace XTC.FMP.MOD.Repository.LIB.MVCS
{

    public class AgentCreateRequestDTO : IDTO
    {
        public AgentCreateRequestDTO(AgentCreateRequest _value)
        {
            Value = _value;    
        }
        public readonly AgentCreateRequest Value;
    }



    public class AgentUpdateRequestDTO : IDTO
    {
        public AgentUpdateRequestDTO(AgentUpdateRequest _value)
        {
            Value = _value;    
        }
        public readonly AgentUpdateRequest Value;
    }



    public class AgentRetrieveResponseDTO : IDTO
    {
        public AgentRetrieveResponseDTO(AgentRetrieveResponse _value)
        {
            Value = _value;    
        }
        public readonly AgentRetrieveResponse Value;
    }



    public class AgentListRequestDTO : IDTO
    {
        public AgentListRequestDTO(AgentListRequest _value)
        {
            Value = _value;    
        }
        public readonly AgentListRequest Value;
    }



    public class AgentListResponseDTO : IDTO
    {
        public AgentListResponseDTO(AgentListResponse _value)
        {
            Value = _value;    
        }
        public readonly AgentListResponse Value;
    }



    public class AgentSearchRequestDTO : IDTO
    {
        public AgentSearchRequestDTO(AgentSearchRequest _value)
        {
            Value = _value;    
        }
        public readonly AgentSearchRequest Value;
    }



    public class HealthyEchoRequestDTO : IDTO
    {
        public HealthyEchoRequestDTO(HealthyEchoRequest _value)
        {
            Value = _value;    
        }
        public readonly HealthyEchoRequest Value;
    }



    public class HealthyEchoResponseDTO : IDTO
    {
        public HealthyEchoResponseDTO(HealthyEchoResponse _value)
        {
            Value = _value;    
        }
        public readonly HealthyEchoResponse Value;
    }



    public class ModuleCreateRequestDTO : IDTO
    {
        public ModuleCreateRequestDTO(ModuleCreateRequest _value)
        {
            Value = _value;    
        }
        public readonly ModuleCreateRequest Value;
    }



    public class ModuleUpdateRequestDTO : IDTO
    {
        public ModuleUpdateRequestDTO(ModuleUpdateRequest _value)
        {
            Value = _value;    
        }
        public readonly ModuleUpdateRequest Value;
    }



    public class ModuleRetrieveResponseDTO : IDTO
    {
        public ModuleRetrieveResponseDTO(ModuleRetrieveResponse _value)
        {
            Value = _value;    
        }
        public readonly ModuleRetrieveResponse Value;
    }



    public class ModuleListRequestDTO : IDTO
    {
        public ModuleListRequestDTO(ModuleListRequest _value)
        {
            Value = _value;    
        }
        public readonly ModuleListRequest Value;
    }



    public class ModuleListResponseDTO : IDTO
    {
        public ModuleListResponseDTO(ModuleListResponse _value)
        {
            Value = _value;    
        }
        public readonly ModuleListResponse Value;
    }



    public class ModuleSearchRequestDTO : IDTO
    {
        public ModuleSearchRequestDTO(ModuleSearchRequest _value)
        {
            Value = _value;    
        }
        public readonly ModuleSearchRequest Value;
    }



    public class PluginCreateRequestDTO : IDTO
    {
        public PluginCreateRequestDTO(PluginCreateRequest _value)
        {
            Value = _value;    
        }
        public readonly PluginCreateRequest Value;
    }



    public class PluginUpdateRequestDTO : IDTO
    {
        public PluginUpdateRequestDTO(PluginUpdateRequest _value)
        {
            Value = _value;    
        }
        public readonly PluginUpdateRequest Value;
    }



    public class PluginRetrieveResponseDTO : IDTO
    {
        public PluginRetrieveResponseDTO(PluginRetrieveResponse _value)
        {
            Value = _value;    
        }
        public readonly PluginRetrieveResponse Value;
    }



    public class PluginListRequestDTO : IDTO
    {
        public PluginListRequestDTO(PluginListRequest _value)
        {
            Value = _value;    
        }
        public readonly PluginListRequest Value;
    }



    public class PluginListResponseDTO : IDTO
    {
        public PluginListResponseDTO(PluginListResponse _value)
        {
            Value = _value;    
        }
        public readonly PluginListResponse Value;
    }



    public class PluginSearchRequestDTO : IDTO
    {
        public PluginSearchRequestDTO(PluginSearchRequest _value)
        {
            Value = _value;    
        }
        public readonly PluginSearchRequest Value;
    }



    public class StatusDTO : IDTO
    {
        public StatusDTO(Status _value)
        {
            Value = _value;    
        }
        public readonly Status Value;
    }



    public class BlankRequestDTO : IDTO
    {
        public BlankRequestDTO(BlankRequest _value)
        {
            Value = _value;    
        }
        public readonly BlankRequest Value;
    }



    public class BlankResponseDTO : IDTO
    {
        public BlankResponseDTO(BlankResponse _value)
        {
            Value = _value;    
        }
        public readonly BlankResponse Value;
    }



    public class ScopeRequestDTO : IDTO
    {
        public ScopeRequestDTO(ScopeRequest _value)
        {
            Value = _value;    
        }
        public readonly ScopeRequest Value;
    }



    public class ScopeResponseDTO : IDTO
    {
        public ScopeResponseDTO(ScopeResponse _value)
        {
            Value = _value;    
        }
        public readonly ScopeResponse Value;
    }



    public class UuidRequestDTO : IDTO
    {
        public UuidRequestDTO(UuidRequest _value)
        {
            Value = _value;    
        }
        public readonly UuidRequest Value;
    }



    public class UuidResponseDTO : IDTO
    {
        public UuidResponseDTO(UuidResponse _value)
        {
            Value = _value;    
        }
        public readonly UuidResponse Value;
    }



    public class PrepareUploadResponseDTO : IDTO
    {
        public PrepareUploadResponseDTO(PrepareUploadResponse _value)
        {
            Value = _value;    
        }
        public readonly PrepareUploadResponse Value;
    }



    public class FlushUploadResponseDTO : IDTO
    {
        public FlushUploadResponseDTO(FlushUploadResponse _value)
        {
            Value = _value;    
        }
        public readonly FlushUploadResponse Value;
    }



    public class FlagOperationRequestDTO : IDTO
    {
        public FlagOperationRequestDTO(FlagOperationRequest _value)
        {
            Value = _value;    
        }
        public readonly FlagOperationRequest Value;
    }



    public class FlagOperationResponseDTO : IDTO
    {
        public FlagOperationResponseDTO(FlagOperationResponse _value)
        {
            Value = _value;    
        }
        public readonly FlagOperationResponse Value;
    }



    public class FileEntityDTO : IDTO
    {
        public FileEntityDTO(FileEntity _value)
        {
            Value = _value;    
        }
        public readonly FileEntity Value;
    }



    public class PluginEntityDTO : IDTO
    {
        public PluginEntityDTO(PluginEntity _value)
        {
            Value = _value;    
        }
        public readonly PluginEntity Value;
    }



    public class ModuleEntityDTO : IDTO
    {
        public ModuleEntityDTO(ModuleEntity _value)
        {
            Value = _value;    
        }
        public readonly ModuleEntity Value;
    }



    public class AgentEntityDTO : IDTO
    {
        public AgentEntityDTO(AgentEntity _value)
        {
            Value = _value;    
        }
        public readonly AgentEntity Value;
    }



}
